# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from app.schemas import PlateResult as PlateResult, RecognitionResponse as RecognitionResponse, RecognitionStatusEnum as RecognitionStatusEnum
from app.services.pipeline import recognize_plate_image as recognize_plate_image

__all__ = ["PlateResult", "RecognitionResponse", "RecognitionStatusEnum", "recognize_plate_image"]




__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import re
import _frozen_importlib_external
import importlib
import importlib.metadata
import pydantic_settings
import __future__
import collections
import collections.abc
import typing
import loguru
import argparse
import json
import sys
import dataclasses
import datetime
import enum
import pydantic
import time
import contextlib
import asyncer
import fastapi
import fastapi.exceptions
import fastapi.middleware
import fastapi.middleware.cors
import fastapi.responses
import uvicorn
import numpy
import PIL
import ultralytics
import io
import cv2
import logging
import math
import rapidocr